releases:
  - name: appointment-service
    chart: ./charts/appointment-service
    values:
      - ./charts/appointment-service/values.yaml
  - name: patient-service
    chart: ./charts/patient-service
    values:
      - ./charts/patient-service/values.yaml



